# Generated by Django 4.1 on 2022-12-16 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('fechaInscripcion', models.DateField()),
                ('horaInscripcion', models.DateTimeField()),
                ('estado', models.CharField(choices=[['R', 'Reservado'], ['C', 'Completada'], ['A', 'Anulada'], ['N', 'No Asisten']], max_length=1)),
                ('observacion', models.TextField(blank=True, max_length=300, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminario_app.institucion')),
            ],
        ),
    ]
