# Generated by Django 4.1 on 2022-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0004_alter_inscritos_fechainscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='fechaInscripcion',
            field=models.DateField(verbose_name='Fecha Inscripción (YYY-MM-DD)'),
        ),
    ]
